name = "fenliu-router-dev"
main = "src/index.ts"
compatibility_date = "2026-06-28"
workers_dev = true

[[kv_namespaces]]
binding = "ROUTE_KV"
id = "e1d6205e208b4467a9499ef8954dc393"

[[queues.producers]]
binding = "TRACK_QUEUE"
queue = "fenliu-track-events-dev"
